import type { NextPage } from 'next';
import Head from 'next/head';
import React from 'react';

const DevLog: NextPage = () => {
  return (
    <div>
      <Head>
        <title>F西的个人小站-开发日志</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>DevLog</div>
    </div>
  );
};

export default DevLog;
